const posts = [
  {
    id: 0,
    name: "Vincent van Gogh",
    username: "vincey1853",
    location: "Zundert, Netherlands",
    avatar: "img/user-avatar.png",
    altAvatar: "vincey1853 avatar",
    post: "img/post-image.png",
    altPost: "Portrait of Vincent van Gogh",
    comment: "just took a few mushrooms lol",
    likes: 1323,
  },
  {
    id: 1,
    name: "Gustave Courbet",
    username: "gus1819",
    location: "Ornans, France",
    avatar: "img/user-avatar-2.png",
    altAvatar: "gus1819 avatar",
    post: "img/post-image-2.png",
    altPost: "Portrait of Gustave Courbet",
    comment: "i'm feelin a bit stressed tbh",
    likes: 850,
  },
  {
    id: 2,
    name: "Joseph Ducreux",
    username: "jd1735",
    location: "Paris, France",
    avatar: "img/user-avatar-3.png",
    altAvatar: "jd1735 avatar",
    post: "img/post-image-3.png",
    altPost: "Portrait of Joseph Ducreux",
    comment:
      "gm friends! which coin are YOU stacking up today?? post below and WAGMI!",
    likes: 1008,
  },
  {
    id: 3,
    name: "Paul Cezanne",
    username: "pc1839",
    location: "Aix-en-provence, France",
    avatar: "img/user-avatar-4.png",
    altAvatar: "pc1839 avatar",
    post: "img/post-image-4.png",
    altPost: "Portrait of Paul Cezanne",
    comment:
      "Do you love to have conversation with intelligent people? I do, I love debates as well and augmented statements.",
    likes: 227,
  },
  {
    id: 4,
    name: "Antony van Dyck",
    username: "ad1632",
    location: "Antwerp, Netherlands",
    avatar: "img/user-avatar-5.png",
    altAvatar: "ad1632 avatar",
    post: "img/post-image-5.png",
    altPost: "Portrait of Antony van Dyck",
    comment:
      "Because why exactly? And how it can resolve my problems? I don’t see any way.",
    likes: 965,
  },
  {
    id: 5,
    name: "Jan van Eyck",
    username: "je1441",
    location: "Maaseik, Netherlands",
    avatar: "img/user-avatar-6.png",
    altAvatar: "je1441 avatar",
    post: "img/post-image-6.png",
    altPost: "Portrait of Jan van eyck",
    comment:
      "Because why exactly? And how it can resolve my problems? I don’t see any way.",
    likes: 965,
  },
];

export default posts;
